### ISSUE TITLE
Kernel Compiling

### ISSUE THREAD

**Issue by PabloGirol** [turex/siberia_hi6250_kernel#1]
I cant seem to be able to compile this kernel by any means
Here is what i do:
clone the repo
`make clean`
`make mrproper`
`make siberia_defconfig`
`make -j12 O=../out`
 
And this is the error
![image](https://user-images.githubusercontent.com/47150336/154809845-046e47d1-20b0-4bc6-bea0-a6529b4c399e.png)

Toolchain used is aarch64-linux-android-6.x-kernel-linaro, i tried with 5.x and other toolchains with the same error

**Comment by PabloGirol** [comment]
Upon further inspection turns out that this lines were broken (reported errors making make clean)
in: drivers/connectivity/hisi/platform/Makefile
![image](https://user-images.githubusercontent.com/47150336/154811437-247ad679-6bfc-4d45-84fa-d4513b494ced.png)
replaced to:
`HI1102_DRIVER_BUILTIN_PATH ?= drivers/connectivity/hisi`

and in: drivers/connectivity/hisi/wifi/Makefile
![image](https://user-images.githubusercontent.com/47150336/154811486-df0747cf-37cb-46ef-80cf-88ca825305a1.png)
with the same variable


Error thrown while doing make clean: 
![image](https://user-images.githubusercontent.com/47150336/154811543-330fc280-c371-43ae-a03d-a53067598134.png)

Similar error with the wifi one

**Comment by turex** [comment]
Hi

Try with gcc 7.5 by linaro (be careful to use aarch64-elf)
